// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9LlnL-ZfYA1CXAP2RrgU1bPiLAiQvB3A',
    appId: '1:338430253813:web:42288bb947ada6c7ed43bc',
    messagingSenderId: '338430253813',
    projectId: 'tiktok-b7235',
    authDomain: 'tiktok-b7235.firebaseapp.com',
    storageBucket: 'tiktok-b7235.firebasestorage.app',
    measurementId: 'G-JEFGK7G0NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeXZwp5AZHHhMv9KjpuyBtkIhANVwZeYM',
    appId: '1:338430253813:android:87c257584cca1835ed43bc',
    messagingSenderId: '338430253813',
    projectId: 'tiktok-b7235',
    storageBucket: 'tiktok-b7235.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiD1ThmKxB1Akx8KpFTyzA3y6gv_4wb74',
    appId: '1:338430253813:ios:62a1d58ec6edf71ced43bc',
    messagingSenderId: '338430253813',
    projectId: 'tiktok-b7235',
    storageBucket: 'tiktok-b7235.firebasestorage.app',
    iosBundleId: 'com.example.tickTock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiD1ThmKxB1Akx8KpFTyzA3y6gv_4wb74',
    appId: '1:338430253813:ios:62a1d58ec6edf71ced43bc',
    messagingSenderId: '338430253813',
    projectId: 'tiktok-b7235',
    storageBucket: 'tiktok-b7235.firebasestorage.app',
    iosBundleId: 'com.example.tickTock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9LlnL-ZfYA1CXAP2RrgU1bPiLAiQvB3A',
    appId: '1:338430253813:web:0f1b9dc7113299c5ed43bc',
    messagingSenderId: '338430253813',
    projectId: 'tiktok-b7235',
    authDomain: 'tiktok-b7235.firebaseapp.com',
    storageBucket: 'tiktok-b7235.firebasestorage.app',
    measurementId: 'G-Q3YEJCG7MP',
  );
}
